### PR TITLE
fix(fluttium_runner): use multi-line string to safely escape patterns for actions

### PR DESCRIPTION
**Pull request by Thithip**
Me again, with the use of multiline notation to avoid a compilation error when using a single quotes on Flow yaml file.

I think a refactor remove my previous fix

Related issue: #87 
Related PR: #88 

## Status

**READY**

## Description

Multi-line notation (with 3 `'` or 3 `"`) allow us to sanitize text patterns with backslashes. 
The main issue was to be able to use single or double quotes on the YAML file to perform actions, like:
```yaml
- expectVisible: "Thithip's awesome app!"
```

Unfortunately a refactor on commit e200a8a61e117060c06907ec5629173d09cadef7 remove my previous fix.

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by wolfenrain — DISMISSED** [review]
Looks good! Will test this a bit more before merging!

**Comment by Thithip** [comment]
Any updates? Have you tested this one?

Plus, can I help you by taking an other issue? I know you are in middle of refactoring, can I make something with that or with something else?

**Comment by wolfenrain** [comment]
> Any updates? Have you tested this one?
> 
> Plus, can I help you by taking an other issue? I know you are in middle of refactoring, can I make something with that or with something else?

Hi sorry I haven't had time to check it and I noticed it has a conflict as well ;-).

I would eventually love some testing on the refactor (#112) but it currently isn't in a useable state, and I am blocking any progress on other issues until that PR is solved as it will allow me to fix the other issues much more easy.

**Comment by Thithip** [comment]
> > Any updates? Have you tested this one?
> > Plus, can I help you by taking an other issue? I know you are in middle of refactoring, can I make something with that or with something else?
> 
> Hi sorry I haven't had time to check it and I noticed it has a conflict as well ;-).
> 
> I would eventually love some testing on the refactor (#112) but it currently isn't in a useable state, and I am blocking any progress on other issues until that PR is solved as it will allow me to fix the other issues much more easy.

Oh, I'm so sorry about the conflit, I forgot to update my fork before creating the PR 😬
Now it's up to date, I'm after `main` branch, so there will be no more conflicts.

I would love to help you with Fluttium, so maybe I can at least:
- try to put my PR after #112 
- and maybe try to help you with #112 ? I will pull this branch and see if I can help.

I totally understand you will block other PR because you are in the middle of the BIG refacto. But this issue is something already done in PR #88 few months ago, and some refacto erase my contribution. And in french langage, there is lot of single quote as`'` 🫠

But I will wait, not a problem, really ✌️

**Comment by wolfenrain** [comment]
> > > Any updates? Have you tested this one?
> > > Plus, can I help you by taking an other issue? I know you are in middle of refactoring, can I make something with that or with something else?
> > 
> > 
> > Hi sorry I haven't had time to check it and I noticed it has a conflict as well ;-).
> > I would eventually love some testing on the refactor (#112) but it currently isn't in a useable state, and I am blocking any progress on other issues until that PR is solved as it will allow me to fix the other issues much more easy.
> 
> Oh, I'm so sorry about the conflit, I forgot to update my fork before creating the PR 😬 Now it's up to date, I'm after `main` branch, so there will be no more conflicts.
> 
> I would love to help you with Fluttium, so maybe I can at least:
> 
> * try to put my PR after [feat: add support for custom actions #112](https://github.com/wolfenrain/fluttium/pull/112)
> * and maybe try to help you with [feat: add support for custom actions #112](https://github.com/wolfenrain/fluttium/pull/112) ? I will pull this branch and see if I can help.
> 
> I totally understand you will block other PR because you are in the middle of the BIG refacto. But this issue is something already done in PR #88 few months ago, and some refacto erase my contribution. And in french langage, there is lot of single quote as`'` 🫠
> 
> But I will wait, not a problem, really ✌️

That would be appreciated! I really should get back into the refactor, gotten a bit busy and then I never got back into the groove of the refactor.

I wouldn't mind merging this and #125 before the refactor just to unblock some people. But that would indeed mean that your contribution to that feature would disappear (but not your commits ;-)

I'll set some time apart this week to at least get the ball rolling again as it is near completion functional wise

**Comment by Thithip** [comment]
It's not a big deal if my contribution disappears, the main goal of my contribution is to allow using single or double quotes into Fluttium, not putting my name into the contribution list of the repo 😅

My main point is: if it's simplier for you to add this by yourself in the big refacto, it's totally ok for me to wait. I just want you to not forget this "feature", don't care if this come from my PR or not.


I've taken a look in your pending work. It looks really nice this new way to put `Action` into the Fluttium chore, and allow everybody to create custom actions! 
I've tried to run and fix tests. I've fixed it, but I think some logics is beyond me, and I don't want to break something in your current refacto.
But I will be glad to help you by developing new `CustomActions`, such as `LongPress`, `Drag` or `ErasingText`
_(but I think this is not the right PR to discuss that...)_

**Comment by Thithip** [comment]
Fixed by #112 ! ✌️

**Pull request closed without merging**
